### PR TITLE
Bugfix/wifi drops

### PR DESCRIPTION
**Pull request by mhlmhl**
wlan_check script to check for network problems and restart network if any are found

### CODE REVIEW

**Review by glossyio — CHANGES_REQUESTED** [review]
Change:
- Setup script needs to be restored (see my commit on the same branch- b8f064039a2bf55d9443e13e310db5a5ef76b6f8)
- If crontab.jobs is meant to be piped to contab, add line in setup for that
- correct function name in wlan_check.sh
- provide a log message in wlan_check to know the script ran (even without error)

How are we handling the /var/log/wlan_check.log script so it doesn't get too big?

**Comment by glossyio** [comment]
Regarding the logging capabilities- `/var/log` worked well for testing this; however, would it be better to integrate it into our system logs?  e.g. getting it into journalctl with `system-cat` or `logger`?  https://www.baeldung.com/linux/systemd-journal-message-terminal

**Comment by mhlmhl** [comment]
> * Setup script needs to be restored (see my commit on the same branch- [b8f0640](https://github.com/glossyio/traffic-monitor/commit/b8f064039a2bf55d9443e13e310db5a5ef76b6f8))
Done (restored my version which had change to setup crontab jobs)

> * If crontab.jobs is meant to be piped to contab, add line in setup for that
Done

> * correct function name in wlan_check.sh
I don't see this error.  Maybe not in my copy...

> * provide a log message in wlan_check to know the script ran (even without error)
Done

> How are we handling the /var/log/wlan_check.log script so it doesn't get too big?
Per other comment, switched to using systemd, which handles log rotation

**Comment by mhlmhl** [comment]
> Regarding the logging capabilities- `/var/log` worked well for testing this; however, would it be better to integrate it into our system logs? e.g. getting it into journalctl with `system-cat` or `logger`? https://www.baeldung.com/linux/systemd-journal-message-terminal

Done

**Review by glossyio — COMMENTED** [review]
I removed a few log lines we used for visibility in debugging and renamed a couple output fields to reflect changes to code.

A couple things for improvement on this script:  
- If the TM is intended to be non-internet-connected (do not want to connect to internet), but perhaps connected to LAN or no network at all; can we suspend this script from running??  How do we want to handle that?
- When the first network connectivity `_repeat_command()` error happens, do we even need to run subsequent ones?  Can we jump it to the end to have it reset immediately?

**Review by glossyio — APPROVED** [review]
Besides the potential improvement comments, this script works well, keeps the RPi online, and is low-impact on device resources. Let's bring it in!

**Pull request merged**
